FROM yiisoftware/yii2-php:8.1-fpm-nginx

ARG SOURCE

WORKDIR /app
COPY . /app/

COPY ./docker/$SOURCE/nginx.conf /etc/nginx/conf.d/default.conf

RUN php init --env=Production --overwrite=All

COPY ./docker/php/uploads.ini /usr/local/etc/php/
COPY ./docker/php.conf /usr/local/etc/php-fpm.d/zz-docker.conf

RUN chown -R www-data:www-data /app
RUN chmod -R 0777 /app/recruitment
RUN chmod -R 777 /app/frontend/web

EXPOSE 9000