FROM ubuntu

WORKDIR /app

RUN apt update && \
    add-apt-repository ppa:deadsnakes/ppa  && \
    apt install python3.8

COPY req.txt /app/
RUN pip3 install -r req.txt

COPY . /app/

EXPOSE 5000

CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0"]